language: node_js
node_js:
- '8'
addons:
  hosts:
  - travis.dev
  - joshkalderimis.com
before_install:
- openssl aes-256-cbc -K $encrypted_ff617dab70d7_key -iv $encrypted_ff617dab70d7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host sshali.huoqishi.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- npm run test
after_success:
- npm prune --production
- tar -jcf chat-server.tar.bz2 *
- scp chat-server.tar.bz2 root@sshali.huoqishi.net:/isc/huoqishi
- ssh root@sshali.huoqishi.net 'tar -jxf chat-server.tar.bz2
  -C chat-room'
- ssh root@sshali.huoqishi.net 'cd chat-room && (forever stop index.js & forever
  start index.js )'
addons:
  ssh_known_hosts: 
  - sshali.huoqishi.net
  - 118.190.88.193