language: node_js
node_js:
- '8'
addons:
  hosts:
  - travis.dev
  - joshkalderimis.com
before_install:
- openssl aes-256-cbc -K $encrypted_ff617dab70d7_key -iv $encrypted_ff617dab70d7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host sshali.huoqishi.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- npm run test
after_success:
- npm prune --production # 删除 devDepencies
- rsync -av --exclude ".git" --exclude "node_modules"  ./  root@sshali.huoqishi.net:/isc/huoqishi/chat-room
- ssh root@sshali.huoqishi.net "/isc/huoqishi/chat-room/test.sh"
- cd /isc/huoqishi/chat-room&&npm install&&(forever stop index.js & forever
  start index.js )'
addons:
  ssh_known_hosts: 
  - sshali.huoqishi.net
  - 118.190.88.193