language: node_js
node_js:
- '8'
addons:
  hosts:
  - travis.dev
  - joshkalderimis.com
before_install:
- openssl aes-256-cbc -K $encrypted_ff617dab70d7_key -iv $encrypted_ff617dab70d7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
script:
- npm run test
after_success:
- npm prune --production
- tar -jcf chat-server.tar.bz2 *
- scp chat-server.tar.bz2 root@alissh.huoqishi.net:/isc/huoqishi
- ssh root@alissh.huoqishi.net 'mkdir -p chat-room && tar -jxf chat-server.tar.bz2
  -C chat-room'
- ssh root@alissh.huoqishi.net 'cd chat-server && (forever stop index.js & forever
  start index.js )'
addons:
  ssh_known_hosts: 118.190.88.193